### ISSUE TITLE
Sync GitHub, docs, crates and examples

### ISSUE THREAD

**Issue by rimutaka** [softprops/dynomite#118]
## 💡 Feature description
The code in master branch is ahead of https://lessis.me/dynomite/dynomite/index.html, https://docs.rs/dynomite/0.8.2/dynomite/ and https://crates.io/crates/dynomite.

The ReadMe on GitHub refers to https://lessis.me/dynomite/dynomite/index.html for API docs, which is behind.

#### Suggestion

1. Keep master branch as the official release version, develop in feature or dev branches.
2. Publish to crates.io and docs on merge into master
3. Keep the ReadMe to the minimum as it is now, refer to examples and docs.rs as the source of truth for "how to use this code"

It looks like https://github.com/softprops/dynomite/blob/master/.github/workflows/main.yml already does what I described. Is it not run?

**Comment by softprops** [comment]
It's current. I caught me on a release day. I'll be releasing 0.9

**Comment by softprops** [comment]
Sry I didn't reply directly to the suggestions.

> Keep master branch as the official release version, develop in feature or dev branches.

I use release tags for this purpose. I've been considering renaming master to develop though.

> Publish to crates.io and docs on merge into master

I have to links to docs one for the release and one for latest. Latest is always what's on master

> Keep the ReadMe to the minimum as it is now, refer to examples and docs.rs as the source of truth for "how to use this code"

I typically don't change the release me until the relative time of a new release. Since I tag releases you can always visit that tag to see the examples for that release.

**Comment by rimutaka** [comment]
Doug, I was coming from the (not so experienced) user point view. Let's see if it all syncs up after you do a release ...
